spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/auth
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
